### PR TITLE
Added timer job to the list

### PR DESCRIPTION
**Pull request by estruyf**
Added timer jobs to the list.

### CODE REVIEW

**Comment by waldekmastykarz** [comment]
Nice suggestion @estruyf. What would be a recommended alternative to timer jobs?

**Comment by estruyf** [comment]
Azure WebJobs / Azure Functions that is also what I added into the table as a suggestion, but that focusses on Online only. Maybe if we add PowerShell as a scheduled task, that can be a good alternative for on-prem in combination with PnP PowerShell or PnP Core.

**Comment by waldekmastykarz** [comment]
Sorry, I missed Functions and Azure WebJobs since they were only mentioned in the guidance for TimerJobs. Perhaps it would be good to include them as a separate recommendation under 'Do' for implementing long-running operations. It would also be good to make a distinction between the scenarios for which Functions and WebJobs are suitable, as Functions have limited execution time.

Recommendation for on-prem would also be a nice addition. Both PowerShell and a console app attached to a scheduled task are a suitable alternative and I guess it's a matter of preference/organization policies which one you choose. Nevertheless, both are a valid approach.

**Comment by estruyf** [comment]
Will add it, although the difference between an Azure WebJob and Function depends on the plan you took. When your function is running on a consumption plan it has that 5-minute limit, but when running on an App Service plan the limit is gone. So, that would give you the same experience as a web job, but it is easier to manage.

For on-prem it indeed depends on the customer. Many of them will like the PowerShell approach because that allows an IT-Pro to be in control and do changes.

**Comment by estruyf** [comment]
Added the long-running operations information in PR #10

**Comment by waldekmastykarz** [comment]
Even though you might not have a limit on Functions when using a different plan, they weren't intended to be used for long-runing operations so it would be good if the guidance differentiated on that. This is by the way mentioned in the Azure Functions Best Practices doc @ https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices

**Pull request merged**
